import turtle
import random
screen = turtle.Screen()
screen.screensize(500,500)
screen.bgcolor('blue')
t = turtle.Turtle()
t2=turtle.Turtle()
t3=turtle.Turtle()
t2.hideturtle()
t3.hideturtle()
FORCE_FACTOR = 30

#intro screen
t2.penup()
t2.pendown()
#circle
t.penup()
t.goto(0, 100)
t.pendown()
t.pencolor('black')
t.fillcolor('black')
t.begin_fill()
t.circle(75)
t.end_fill()
t2.write('Introduction To myself', font=("ariel", 30, "italic"), align="center")
round = input("Press Enter to Continue: ")
t2.clear()

#second screen
t.penup()
t.goto(60, 170)
t.pendown()
t.speed(0)
t.setheading(135)
t.fillcolor('cyan')
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()
t2.penup()
t2.pendown()
screen.bgcolor('green')
t2.write('Favorite Foods Tacos Chicken Rice', font=("ariel", 30, "italic"), align="center")
t. penup()
t.goto(-150, -50)
t. pendown ()
screen.addshape('chicken.gif')
t. shape('chicken.gif')
t. stamp()
t. shape( 'classic')
t. penup()
t.goto(150, -50)
t. pendown ()
screen.addshape('rice.gif')
t. shape('rice.gif')
t. stamp()
t. shape( 'classic')
round = input("Press Enter to Continue: ")
t2.clear()


#third screen
screen.bgcolor('red')
t2.pendown()
t2.write('Favorite Hobbies soccer hanging out sleeping ', font=("ariel", 30, "italic"), align="center")     
round = input("Press Enter to Continue: ")
t2.clear()
#fourth screen
screen.bgcolor('white')
t2.pendown()
t2.write('Favorite Movie Spider-Man', font=("ariel", 30, "italic"), align="center")
round = input("Press Enter to Continue: ")
t2.clear()
#fifth screen
screen.bgcolor('purple')
t2.pendown()
t2.write('Favorite Sport soccer', font=("ariel", 30, "italic"), align="center")
round = input("Press Enter to Continue: ")
t2.clear()